# docker-compose.yml
version: '3.8'

services:
  mindcraft:
    build: .
    container_name: mindcraft_bot
    restart: unless-stopped
    ports:
      - "3000-3003:3000-3003"
      - "55916:55916"
    volumes:
      - ./:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command: node main.js
